### ISSUE TITLE
sensors connectivity package ver 0.1 in airapkgs and aira image

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#101]
First release of [sensors-connectivity](https://github.com/airalab/sensors-connectivity) repo with COM-port data reading example of source code. Testing with air pollution sensor NOVA PM sds011.

**Comment by ensrationis** [comment]
https://github.com/airalab/sensors-connectivity/pull/1 done , but should we add this package in airapkgs ? @PavelSheremetev @Vourhey @akru

**Comment by Vourhey** [comment]
I think it's not a problem to create a nixos service for the package. Enabling/Disabling the service would be as easy as:
```
services.connectivity.enable = true;
```
assuming we use default settings. And more advanced usage is
```
services.connectivity.enable = true;
services.connectivity.config = ''
  general:
    port: "/dev/ttyUSB0"  # COM port of the device
    read-interval: 300    # time between two measurements in seconds
    geo: ""               # Geo coordinates as latitude,longitude
  luftdaten:
    enable: true          # whether or not publish to https://luftdaten.info/
  robonomics:
    enable: true          # enable use of Robonomics Network
    result: true          # publish Result message
    demand: false         # publish Demand message
    model: ""             # Agent's model (IPFS hash)
    token: ""             # Ethereum address of ERC20 token
    lighthouse: ""        # Name of lighthouse, e.g. airalab.lighthouse.5.robonomics.eth
    validator: "0x0000000000000000000000000000000000000000"
    validatorFee: 0
  datalog:
    enable: false         # enable use of Datalog Robonomics subcommand
    path: ""              # path to Robonomics execution file
    suri: ""              # private key of publisher account
    remote: "wss://substrate.ipci.io"
    dump-interval: 3600   # time between two transactions in seconds
  dev:
    sentry: ""
'';
```
